# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 524db201a605e03b1d7e1ddcbe0e6536c76e589fba902a377b4c2511930970726f186f65c6cad448f02175035d7e031edee01a37ce774bff15f9aefec7fe3f79

test:
  secret_key_base: 411a1cc96d79cb518af7790cf841a7c3c17d8e3dcd6f9a3009c0ce2bab5f0b853a3ac571d322afed08b3d989bc89f02c4636f5cc13d0cf1c5ec58c079161ee17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 524db201a605e03b1d7e1ddcbe0e6536c76e589fba902a377b4c2511930970726f186f65c6cad448f02175035d7e031edee01a37ce774bff15f9aefec7fe3f79
  # don't want to bother creating this environment variable, this isn't a bank
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
